UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/xiaomi-watch-s3.jpeg', MainImage = 'https://localhost:7279/uploads/products/xiaomi-watch-s3.jpeg' WHERE Id = 41;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/xiaomi-watch-s3.jpeg' WHERE ProductId = 41;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/jbl-charge-5.jpg', MainImage = 'https://localhost:7279/uploads/products/jbl-charge-5.jpg' WHERE Id = 46;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/jbl-charge-5.jpg' WHERE ProductId = 46;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/anker-325-powercore.jpg', MainImage = 'https://localhost:7279/uploads/products/anker-325-powercore.jpg' WHERE Id = 49;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/anker-325-powercore.jpg' WHERE ProductId = 49;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/xiaomi-power-bank-3.jpg', MainImage = 'https://localhost:7279/uploads/products/xiaomi-power-bank-3.jpg' WHERE Id = 50;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/xiaomi-power-bank-3.jpg' WHERE ProductId = 50;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/anker-511-nano-3.jpg', MainImage = 'https://localhost:7279/uploads/products/anker-511-nano-3.jpg' WHERE Id = 51;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/anker-511-nano-3.jpg' WHERE ProductId = 51;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/baseus-type-c-to-c-100w.webp', MainImage = 'https://localhost:7279/uploads/products/baseus-type-c-to-c-100w.webp' WHERE Id = 52;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/baseus-type-c-to-c-100w.webp' WHERE ProductId = 52;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/iphone-15-pro-silicone-case.jpeg', MainImage = 'https://localhost:7279/uploads/products/iphone-15-pro-silicone-case.jpeg' WHERE Id = 53;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/iphone-15-pro-silicone-case.jpeg' WHERE ProductId = 53;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/s24-ultra-spigen-case.jpg', MainImage = 'https://localhost:7279/uploads/products/s24-ultra-spigen-case.jpg' WHERE Id = 54;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/s24-ultra-spigen-case.jpg' WHERE ProductId = 54;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/baseus-lanyard-strap.webp', MainImage = 'https://localhost:7279/uploads/products/baseus-lanyard-strap.webp' WHERE Id = 56;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/baseus-lanyard-strap.webp' WHERE ProductId = 56;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/baseus-hand-strap.webp', MainImage = 'https://localhost:7279/uploads/products/baseus-hand-strap.webp' WHERE Id = 57;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/baseus-hand-strap.webp' WHERE ProductId = 57;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/airpods-pro-2-spigen-case.jpg', MainImage = 'https://localhost:7279/uploads/products/airpods-pro-2-spigen-case.jpg' WHERE Id = 58;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/airpods-pro-2-spigen-case.jpg' WHERE ProductId = 58;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/tab-s9-ultra-keyboard-cover.jpg', MainImage = 'https://localhost:7279/uploads/products/tab-s9-ultra-keyboard-cover.jpg' WHERE Id = 59;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/tab-s9-ultra-keyboard-cover.jpg' WHERE ProductId = 59;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/iphone-15-pro-max-mipow.png', MainImage = 'https://localhost:7279/uploads/products/iphone-15-pro-max-mipow.png' WHERE Id = 60;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/iphone-15-pro-max-mipow.png' WHERE ProductId = 60;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/s24-ultra-zeelot.jpg', MainImage = 'https://localhost:7279/uploads/products/s24-ultra-zeelot.jpg' WHERE Id = 61;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/s24-ultra-zeelot.jpg' WHERE ProductId = 61;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/airpods-3-baseus-case.jpg', MainImage = 'https://localhost:7279/uploads/products/airpods-3-baseus-case.jpg' WHERE Id = 62;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/airpods-3-baseus-case.jpg' WHERE ProductId = 62;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/baseus-folding-bracket.webp', MainImage = 'https://localhost:7279/uploads/products/baseus-folding-bracket.webp' WHERE Id = 63;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/baseus-folding-bracket.webp' WHERE ProductId = 63;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/baseus-gravity-car-mount.webp', MainImage = 'https://localhost:7279/uploads/products/baseus-gravity-car-mount.webp' WHERE Id = 64;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/baseus-gravity-car-mount.webp' WHERE ProductId = 64;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/samsung-evo-select-128gb.png', MainImage = 'https://localhost:7279/uploads/products/samsung-evo-select-128gb.png' WHERE Id = 65;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/samsung-evo-select-128gb.png' WHERE ProductId = 65;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/sandisk-ultra-64gb.jpg', MainImage = 'https://localhost:7279/uploads/products/sandisk-ultra-64gb.jpg' WHERE Id = 66;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/sandisk-ultra-64gb.jpg' WHERE ProductId = 66;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/sandisk-ultra-flair-64gb.jpg', MainImage = 'https://localhost:7279/uploads/products/sandisk-ultra-flair-64gb.jpg' WHERE Id = 67;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/sandisk-ultra-flair-64gb.jpg' WHERE ProductId = 67;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/sandisk-dual-drive-go-128gb.jpg', MainImage = 'https://localhost:7279/uploads/products/sandisk-dual-drive-go-128gb.jpg' WHERE Id = 68;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/sandisk-dual-drive-go-128gb.jpg' WHERE ProductId = 68;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/samsung-t7-1tb.jpg', MainImage = 'https://localhost:7279/uploads/products/samsung-t7-1tb.jpg' WHERE Id = 69;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/samsung-t7-1tb.jpg' WHERE ProductId = 69;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/wd-elements-1tb.jpg', MainImage = 'https://localhost:7279/uploads/products/wd-elements-1tb.jpg' WHERE Id = 70;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/wd-elements-1tb.jpg' WHERE ProductId = 70;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/s25-ultra-zeelot.jpg', MainImage = 'https://localhost:7279/uploads/products/s25-ultra-zeelot.jpg' WHERE Id = 72;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/s25-ultra-zeelot.jpg' WHERE ProductId = 72;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/s25-ultra-mipow-camera.jpg', MainImage = 'https://localhost:7279/uploads/products/s25-ultra-mipow-camera.jpg' WHERE Id = 73;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/s25-ultra-mipow-camera.jpg' WHERE ProductId = 73;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/s25-ultra-spigen-case.jpg', MainImage = 'https://localhost:7279/uploads/products/s25-ultra-spigen-case.jpg' WHERE Id = 74;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/s25-ultra-spigen-case.jpg' WHERE ProductId = 74;
UPDATE Products SET ThumbnailImage = 'https://localhost:7279/uploads/products/s25-ultra-uag-monarch.jpg', MainImage = 'https://localhost:7279/uploads/products/s25-ultra-uag-monarch.jpg' WHERE Id = 75;
UPDATE ProductVariants SET ImageId = 'https://localhost:7279/uploads/products/s25-ultra-uag-monarch.jpg' WHERE ProductId = 75;